Desarrollo-A/beneficiosCMFront

src/sections/auth/jwt/jwt-preRegister-view.jsx, src/sections/auth/jwt/jwt-register-view.jsx
se han hecho cambios en validaciones de
=> cambios en registro

src/api/user.js
Funciones de Api/users actualizadas
=> Funciones de Api/users actualizadas

src/api/especialistas.js, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/utils/axios.js
Se muestran los dias disponibles dependiendo del horario presencial del especialista cuando un beneficiario quiere agendar una cita.
Se agrego modal en el especialista para que el especialista establesca su horario presencial.
Se agrego api para la ruta del especialista.
Se agrego ruta en axios para las llamadas.
=> Show available dates by horario presencial

src/api/calendar-colaborador.js, src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/calendario-formulario.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx
Cambios volados restaurados en API colaborador
=> Cambios volados restaurados en API colaborador

src/routes/sections/dashboard.jsx
Se reparo el enlace al dar click en Perfil en el Popup de usuarios
=> Users popup route bugfix

src/hooks/use-session.js, src/routes/paths.js, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx
Ruta de perfil solucionada y se quito validación para trabajadores de fundación
=> Ruta de perfil solucionada y se quito validacion para fundacion

src/api/calendar-specialist.js, src/routes/sections/dashboard.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/calendar-preview.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx
Correos de usuarios sustituidos para pruebas en la api de especialista y colaborador. Ruta de usuarios externos arreglada, algunos acentos corregidos.
=> Correos de usuarios sustituidos para pruebas y ruta de usuarios externos arreglada

src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/calendar-preview.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx
=> Correos descomentados

src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/overview/calendarioespecialista/view/calendario-view.jsx
Solo los especialistas que tienen asignadas mas sedes presenciales pueden ver el boton de "Establecer horario presencial".
En el colaborador al agendar una nueva cita, ahora podra ver todos los dias habilitados para los especialistas que tienen una sola sede presencial.
=> Presencial bugfix

src/api/especialistas.js, src/sections/overview/dash/grafica-metas.jsx, src/sections/overview/dash/view/dash-view.jsx, src/utils/axios.js
Se creo funcion en la api de especialista para obtener las metas y citas.
Se modifico el componente de grafica metas para usar los valores obtenidos del back.
Se quito el array de citas para el componente de grafica metas en el dash-view.
Se agrego ruta para obtener los datos de las metas y citas en el back.
=> Citas en dashboard

src/sections/encuestas/crear-nueva-encuesta-formulario.jsx, src/sections/encuestas/encuestas-tabla-barra.jsx, src/sections/encuestas/encuestas-tabla-filtros.jsx, src/sections/encuestas/encuestasLista.jsx
=> select encuestas

src/api/especialistas.js, src/sections/overview/dash/grafica-metas-area.jsx, src/sections/overview/dash/view/dash-view.jsx, src/utils/axios.js, src/utils/format-string.js
Nueva grafica para visualizar las citas y metas de todos los especialistas solo para el administrador de la especialidad.
=> Chart metas for admin

src/sections/overview/calendarioespecialista/view/cancelEventDialog.jsx, src/sections/overview/calendarioespecialista/view/lista.jsx, src/sections/overview/calendarioespecialista/view/pendingModal.jsx
se agrega el loading button y se valida el autocomplete
=> cambios en calendario especialista

src/sections/calendariobeneficiario/appointment-schedule.jsx
Validación de encadenamiento de especialista, modalidades y beneficios
=> Validación de encadenamiento de especialista, modalidades y beneficios

src/sections/overview/dash/barra-encuesta.jsx, src/sections/overview/dash/porcentaje-encuesta.jsx, src/sections/overview/dash/view/dash-view.jsx
Se quitaron algunos warning que aparecian en los selecs.
=> Cleaning warning

src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/calendar-preview.jsx
Responsivo en mobile y ajuste de colores en calendario colaborador.
=> Responsivo en mobile y ajuste de colores en calendario colaborador.

src/api/calendar-colaborador.js
Cambios en getAppointments by user
=> Cambios en getAppointments by user

src/sections/reportes/barratareas-tabla-citas.jsx, src/sections/reportes/filtros-tabla-citas.jsx, src/sections/reportes/modal-editar-citas.jsx, src/sections/reportes/view/historial-reportes-view.jsx
Ajuste a justificación y contadores
=> Historial Reportes

src/api/calendar-colaborador.js, src/api/calendar-specialist.js, src/layouts/dashboard/header.jsx, src/pages/dashboard/dash.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/evaluate-dialog.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx, src/sections/calendariobeneficiario/view/calendar-view.jsx, src/sections/usuarios/userList.jsx, src/utils/axios.js
Validación de queries de rich y ventana de pendientes validada
=> Validación de queries de rich y ventana de pendientes validada

src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/usuarios/edit-user-dialog.jsx, src/sections/usuarios/user-table-row.jsx
=> Error batch usuarios externos

src/components/hook-form/rhf-date-picker.jsx, src/sections/overview/calendarioespecialista/view/agenda-dialog.jsx
Se agrego validacion en caso de que la fecha final sea menor a la fecha inicial.
Se paso el localization provider al hook del date picker.
Se cambio alertas en caso de que no se elija sede.
=> Disable fechas calendario horario

src/sections/citas/view/citas-view.jsx, src/sections/overview/dash/view/dash-view.jsx, src/sections/usuarios/view/user-list-view.jsx
Corrección servicio api update ch
=> Corrección servicio api update ch

src/api/calendar-colaborador.js, src/auth/context/jwt/utils.js, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx
Dato areabeneficio colocado en usuario al registrar cuenta
=> Dato areabeneficio colocado en usuario al registrar cuenta

.env.production
=> CONFIG BASE URL PROD

src/layouts/dashboard/header.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/calendar-preview.jsx
Error de enviar notificación solucionada
=> Error de enviar notificación solucionada

src/layouts/auth/classic.jsx, src/sections/auth/jwt/jwt-login-view.jsx, src/sections/auth/jwt/jwt-verificacion-view.jsx
Se pierden algunos estilos, imágenes y menú cuando se ingresa al sistema desde un dispositivo móvil.
=> Estilos login

src/sections/auth/jwt/jwt-register-view.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/utils/general.js
Modificaciones de alerta en agenda y funcion cambiada a archivo general
=> Modificaciones de alerta en agenda y funcion cambiada a archivo general

src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/calendar-preview.jsx
Cambios en iconos de preview y acento en notifiacion
=> Cambios en iconos de preview y acento en notifiacion

src/api/calendar-colaborador.js, src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/utils/axios.js
Estandarización de mayúsculos en los endpoints.
=> Estandarización de mayúsculas en los endpoints

src/auth/context/jwt/auth-provider.jsx, src/utils/axios.js
Configuación de headers en fetchers para el envío de token
=> Configuación de headers en fetchers para el envío de token

src/api/user.js, src/sections/usuarios/edit-user-dialog.jsx, src/sections/usuarios/userList.jsx, src/sections/usuarios/view/user-list-view.jsx, src/utils/axios.js
Modulo lamat adaptado a su nueva tabla de usuariosexternos
=> Modulo lamat adaptado a su nueva tabla de usuariosexternos

src/api/avisos-privacidad.js, src/api/especialistas.js, src/sections/overview/agenda/agenda-dialog.jsx, src/sections/overview/calendarioespecialista/view/agenda-dialog.jsx, src/sections/privacidad/aviso-privacidad-general.jsx
Se remplazo el fetch de presencialxsede y se utilizo nuestro fetcherPost y se agregó el token al fetch
=> Modificación a presencialxsede

src/api/encuestas.js, src/api/verificacion.js, src/sections/auth/jwt/jwt-preRegister-view.jsx, src/sections/auth/jwt/jwt-verificacion-view.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/overview/calendarioespecialista/view/lista.jsx
Last_id y nombre de cita resuelto.
=> Last_id y nombre de cita resuelto.

src/api/calendar-colaborador.js, src/api/calendar-specialist.js, src/layouts/dashboard/header.jsx, src/sections/auth/jwt/jwt-preRegister-view.jsx, src/sections/auth/jwt/jwt-register-view.jsx, src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/calendar-preview.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx, src/sections/overview/calendarioespecialista/view/colors-dialog.jsx, src/sections/overview/calendarioespecialista/view/lista.jsx, src/sections/reportes/components/reporte-pacientes/modal-historial-citas.jsx, src/utils/axios.js
Implementación de metodo pago y ajustes generales
=> Implementación de metodo pago y ajustes generales

src/layouts/dashboard/header.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/calendar-preview.jsx
Cambio de lógica al enviar notificaciones y al agendar el evento de google
=> Cambio de lógica al enviar notificaciones y al agendar el evento de google

src/api/calendar-specialist.js
Se implementó el envió de correos al colaborador notificando una cita pendiente de pago agendada por el especialista.
=> Envio de email en cita pendiente

src/sections/calendariobeneficiario/calendar-dialog.jsx, src/utils/general.js
Se mejoraron los días de las fechas festivas.
=> Dias festivos con dia exacto

src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx
Se implementó Loaders de carga en inputs de cita
=> Loaders de carga en inputs de cita

public/Documentacion.php, src/assets/illustrations/seo-illustration.jsx, src/components/image/image.jsx, src/components/settings/drawer/base-option.jsx, src/layouts/dashboard/header.jsx, src/layouts/main/nav/mobile/index.jsx, src/theme/css.js
=> Icons fixed

src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx
=> Inputs con valor y loaders en agendar cita

src/sections/auth/jwt/jwt-preRegister-view.jsx, src/sections/calendariobeneficiario/modal-terminos.jsx, src/sections/privacidad/aviso-privacidad-general.jsx, src/sections/reportes/components/historial-reportes/filas-tabla-citas.jsx
- Ajustes para omitir consulta y subida de archivos a bucket de google
- Solución de ticket de registro de usuario (validación permitida para correos .mx)
=> Ajustes en avisos de privacidad y corrección de validación correo

src/components/hook-form/rhf-text-field.jsx, src/sections/auth/jwt/jwt-preRegister-view.jsx
- Los correos se consultan y registran del lado de beneficios
=> Actualización de correos

src/sections/auth/jwt/jwt-preRegister-view.jsx, src/sections/calendariobeneficiario/style.css, src/sections/calendariobeneficiario/view/calendar-view.jsx, src/sections/gestor/usuarios-components/modal-usuarios.jsx, src/sections/gestor/usuarios-components/table-row-usuarios.jsx, src/sections/gestor/view/usuarios-view.jsx
-Se requiere dar de alta nuevos dominios de correo electrónico en el sistema
- Se requiere mejora para que se pueda consultar en el sistema a los colaboradores que se encuentran dados de alta en el sistema
- Se bloquea click a calendario, solo da click en eventos creados y nuevos estilos para boton de nueva cita
=> Btn cita, tabla usuarios, dominios, login

src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/confirm-doble-payment.jsx, src/sections/calendariobeneficiario/pendingModalUser.jsx, src/sections/calendariobeneficiario/view/calendar-view.jsx
Se agregó una ventana de confirmación de pago para aquellas situaciones en la que ya se halla intentado pagar una cita.
=> Confirmación doble de pago

src/sections/calendariobeneficiario/confirm-doble-payment.jsx
Leyenda de pagar con paréntesis.
=> Confirmación doble pago

src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/confirm-doble-payment.jsx
Quotes para la leyenda de pagar
=> Quotes para la leyenda de pagar

src/api/calendar-colaborador.js, src/sections/ayuda/components/ayuda/manuales.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx, src/sections/calendariobeneficiario/confirm-doble-payment.jsx, src/sections/calendariobeneficiario/view/calendar-view.jsx, src/sections/overview/calendarioespecialista/view/lista.jsx, src/sections/overview/dash/grafica-encuestas.jsx, src/utils/axios.js, src/utils/contextGeneralProvider.jsx
SEDES: Se repetían las sedes para el especialista al asignar sede de atención, se le agregó en la validación el estatus = 1.
AreaBeneficio: Al registrar un especialista no se le asignaba correctamente el areabeneficio, se le agrego los breaks al switch para que tome bien el dato.
Modalidades: Las modalidades en calendario beneficiario no cargaban, se regresó el cambio a como estaba antes apuntando al getModalities. 
Reagenda: Al reagendar había situaciones que cancelaba la cita y no agendaba la nueva reagenda, esto debido a la validación de total de citas por beneficiario y a citas pendientes. Se quito dicha validación.
=> Ajustes en sedes de especialista, dato de areabeneficio, modalidades en agenda y reagenda, y validaciones reagendar

src/sections/calendariobeneficiario/appointment-schedule.jsx, src/sections/calendariobeneficiario/calendar-dialog.jsx
Se deselecciona la fecha en el calendario de citas al cambiar de valor de la cita.
=> Deseleccionar fecha en calendario

src/sections/calendar/beneficiary/dialogs/appointment-scheduled-dialog.jsx
Se removió el fragmento de código que consultaba los datos de la ultima cita para preseleccionar las opciones de su cita previa al agendar nuevamente.
=> Se remueve el proceso de cargar los datos de la ultima cita

src/api/calendar-specialist.js, src/sections/calendar/beneficiary/dialogs/appointment-scheduled-dialog.jsx, src/sections/calendar/beneficiary/pendingModalUser.jsx
Cambio precio operativos en la nueva versión de calendario
=> Cambio precio operativos en la nueva versión de calendario

src/sections/ayuda/components/gestor-ayuda/manuales/estatusDialog.jsx, src/sections/calendar/beneficiary/dialogs/confirm-cancel-dialog.jsx, src/sections/encuestas/modal-editar-dias.jsx
Se corrigió la palabra de está seguro a por: estás seguro, esto en las modales de confirmacion.
=> Falta ortógrafica de palabra: estás

src/sections/encuestas/modal-editar-dias.jsx
Se soluciono el error en el modal de editar días.
=> Error en el modal de editar días

src/layouts/dashboard/header.jsx, src/sections/calendar/beneficiary/evaluate-dialog.jsx, src/sections/calendar/beneficiary/pendingModalUser.jsx, src/sections/calendar/specialist/dialogs/create-event-dialog.jsx
1.- Listado de pacientes 'Vacia' arreglada, no se tenia un apellido por lo que hacia la concatenación de nombre completo mal.
2.- Se retiro a los de LAMAT de la lista de pacientes.
3.- Se agregó a los especialistas y administradores en la lista de pacientes de otro especialista.
4.- Se cambió el titulo de las encuestas.
=> Corrección de incidencias reportadas por tester

src/sections/calendar/beneficiary/evaluate-dialog.jsx
=> Ajuste titulo de encuestas

src/api/calendar-specialist.js, src/sections/calendar/styles/styles.js, src/sections/reportes/components/historial-reportes/barratareas-tabla-citas.jsx, src/sections/reportes/view/historial-reportes-view.jsx
se ha hecho un cambio para que el usuario con rol 2 y permisos 1 pueda ver las citas y cantidad de paciente
=> cambios en el historial de citas

src/sections/reportes/components/historial-reportes/filas-tabla-citas.jsx
Se le agregó la validación que únicamente especialistas (rol 3) puedan añadir justificaciones.
=> Justificación de penalizaciones solo para especialistas

src/api/calendar-specialist.js
Regreso de una validación para agendar citas
=> Regreso de una validación para agendar citas
